name: Docker Image CI

on:
  workflow_dispatch:  # 允许手动触发
  push:               # 允许推送触发
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # 拉取代码

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3 # 登录 Docker Hub
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
  
      - name: Process files
        run: |
          # 包含 CHANGELOG.md
          cp CHANGELOG.md epg/assets/CHANGELOG.md
          
          VERSION=$(TZ="Asia/Shanghai" date +"v%Y.%m.%d")  # 获取北京时间，并转换为 v2024.11.24 格式

          # 更新 manage.html
          sed -i "s|<span id=\"version\">.*</span>|<span id=\"version\">${VERSION}</span>|" epg/assets/html/manage.html
          sed -i "s|assets/css/manage.css|assets/css/manage.css?ver=${VERSION}|g" epg/assets/html/manage.html
          sed -i "s|assets/js/manage.js|assets/js/manage.js?ver=${VERSION}|g" epg/assets/html/manage.html

          # 更新 login.html
          sed -i "s|assets/css/login.css|assets/css/login.css?ver=${VERSION}|g" epg/assets/html/login.html

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          platforms: linux/amd64, linux/arm64, linux/arm/v7
          tags: taksss/php-epg:dev
